feat(ios): added all the required empty methods to inherit them at required place.
appcelerator-modules/ti.nfc pull request #36
Opened 2020-12-15 10:38 UTC by anil-shukla-axway

https://jira.appcelerator.org/browse/MOD-2835

2020-12-15 10:39 UTC, build commented
<!--
  1 failure:  `npm run lint` fa...
  3 warning:  :mag: Can't find ..., guid is inconsist..., SDK version decla...
  1 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  `npm run lint` failed, please check messages below for output.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :mag: Can't find junit reports at `./TESTS-*.xml`, skipping generating JUnit Report.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>guid is inconsistent across platforms. It is 50513178-f1da-40e1-8031-75c08db86d6f in android/manifest and e6caa17f-c084-402c-be84-8df242d94eba in ios/manifest</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>SDK version declared in Jenkinsfile (9.2.0.v20200921095451) does not match iOS' titanium.xcconfig value (9.2.0.GA)</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :bomb: Here's the output of `npm run lint`:
```
> @titanium-sdk/ti.nfc@5.0.0 lint /Users/build/jenkins/workspace/modules_ti.nfc_PR-36
> npm run lint:android && npm run lint:ios && npm run lint:js && npm run lint:docs


> @titanium-sdk/ti.nfc@5.0.0 lint:android /Users/build/jenkins/workspace/modules_ti.nfc_PR-36
> clang-format-lint android/src/**/*.java


> @titanium-sdk/ti.nfc@5.0.0 lint:ios /Users/build/jenkins/workspace/modules_ti.nfc_PR-36
> clang-format-lint ios/Classes/**/*.m ios/Classes/**/*.h

Error: Formatting incorrect on "ios/Classes/TagTechnologyProxy.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='411' length='1'>&#10;</replacement>
<replacement offset='413' length='4'>&#10;</replacement>
<replacement offset='444' length='1'>&#10;</replacement>
<replacement offset='446' length='2'>&#10;</replacement>
<replacement offset='484' length='1'>&#10;</replacement>
<replacement offset='486' length='2'>&#10;</replacement>
<replacement offset='527' length='0'>&#10;</replacement>
<replacement offset='528' length='2'>&#10;</replacement>
<replacement offset='566' length='1'>&#10;</replacement>
<replacement offset='568' length='2'>&#10;</replacement>
<replacement offset='607' length='1'>&#10;</replacement>
<replacement offset='609' length='2'>&#10;</replacement>
</replacements>

Error: Formatting incorrect on "ios/Classes/TagTechnologyProxy.h", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='515' length='1'></replacement>
<replacement offset='571' length='2'>&#10;</replacement>
</replacements>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @titanium-sdk/ti.nfc@5.0.0 lint:ios: `clang-format-lint ios/Classes/**/*.m ios/Classes/**/*.h`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @titanium-sdk/ti.nfc@5.0.0 lint:ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/build/.npm/_logs/2020-12-15T10_39_00_061Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @titanium-sdk/ti.nfc@5.0.0 lint: `npm run lint:android && npm run lint:ios && npm run lint:js && npm run lint:docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @titanium-sdk/ti.nfc@5.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/build/.npm/_logs/2020-12-15T10_39_00_098Z-debug.log
```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3505023695fac58171f29c6008d1ebe1ac660195
</p>

2020-12-16 04:38 UTC, anil-shukla-axway commented
@satinder-singh-axway  @fasihul-axway  Please review this PR.

2020-12-16 08:31 UTC, satinder-singh-axway requested changes

2020-12-16 08:32 UTC, satinder-singh-axway commented
@anil-shukla-axway , can you please address build warnings ?

2020-12-17 06:05 UTC, anil-shukla-axway commented on ios/Classes/TagTechnologyProxy.m
> +}
Yes, I have added the same.

2020-12-17 06:05 UTC, anil-shukla-axway commented on ios/Classes/TagTechnologyProxy.m
> +{
added

2020-12-17 06:39 UTC, satinder-singh-axway requested changes
Please update the PR to merge against a feature branch instead the master.

2020-12-17 06:39 UTC, satinder-singh-axway commented on ios/Classes/TagTechnologyProxy.m
> +{
Where is the ret value value ?

2020-12-17 06:42 UTC, vikas-goyal-axway requested changes
<img width="823" alt="Screenshot 2020-12-17 at 12 11 34 PM" src="https://user-images.githubusercontent.com/38314488/102452831-0bdd7400-4061-11eb-8f4b-9fb0dd65a1ac.png">
@anil-shukla-axway , Also there is 2 build warning, Please look into it

2020-12-17 06:42 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.m
> +  return;
```suggestion
  return [NSNumber numberWithBool:NO];
```

2020-12-17 06:42 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.m
> +  return;
```suggestion
  return [NSNumber numberWithBool:NO];
```

2020-12-17 07:14 UTC, anil-shukla-axway commented on ios/Classes/TagTechnologyProxy.m
> +{
now updated as per suggestion

2020-12-17 07:23 UTC, anil-shukla-axway commented on ios/Classes/TagTechnologyProxy.m
> +  return;
Updated as per suggestion

2020-12-17 07:23 UTC, anil-shukla-axway commented on ios/Classes/TagTechnologyProxy.m
> +  return;
Updated as per suggestion

2020-12-17 07:24 UTC, anil-shukla-axway commented
Updated base branch from 'master' to 'NativeTagSupport'

2020-12-23 09:12 UTC, vikas-goyal-axway requested changes

2020-12-23 09:12 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.h
> +- (void)close:(id)unused;
remove it if this function is not required

2020-12-23 09:12 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.h
> +- (void)restartPolling:(id)unused;
remove it if this function is not required

2020-12-23 09:12 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.h
> +- (NSNumber *)isEnabled:(id)unused;
remove it if this function is not required

2020-12-23 09:12 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.m
> +- (void)restartPolling:(id)unused
remove it if this function is not required

2020-12-23 09:12 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.m
> +- (void)close:(id)unused
remove it if this function is not required

2020-12-23 09:12 UTC, vikas-goyal-axway commented on ios/Classes/TagTechnologyProxy.m
> +- (NSNumber *)isEnabled:(id)unused
remove it if this function is not required

2020-12-29 08:11 UTC, vikas-goyal-axway approved these changes

2020-12-31 09:01 UTC, merged