MOD-2830- Add properties, events and method for TagTechnologyMifareUltralight
appcelerator-modules/ti.nfc pull request #41
Opened 2021-02-04 05:24 UTC by anil-shukla-axway

https://jira.appcelerator.org/browse/MOD-2830

2021-02-04 05:29 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: Here are the artifacts produced:
- <a href="https://jenkins.appcelerator.org/job/modules/job/ti.nfc/job/PR-41/1/artifact/ti.nfc-iphone-3.0.0.zip">ti.nfc-iphone-3.0.0.zip</a>
- <a href="https://jenkins.appcelerator.org/job/modules/job/ti.nfc/job/PR-41/1/artifact/ti.nfc-android-4.0.0.zip">ti.nfc-android-4.0.0.zip</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 89 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f7f48190f5d5fe1068bbb0bc48283b9dad558ae6
</p>

2021-03-01 12:37 UTC, fasihul-axway requested changes

2021-03-01 12:37 UTC, fasihul-axway commented on ios/Classes/TiNfcNativeTagTechnologyProxy.m
> +             if (error != nil) {
May be we can do like 

```suggestion
             [self fireEvent:@"didConnectTag"
                    withObject:@{
                        @"errorCode" : error != nil ? NUMINTEGER([error code]) : NULL,
                        @"errorDescription" : error != nil ? [error localizedDescription] : NULL,
                        @"errorDomain" : error != nil ? [error domain] : NULL,
                      @"tag" : self.tag
                    }];
```

2021-03-02 05:25 UTC, vikas-goyal-axway requested changes

2021-03-02 05:25 UTC, vikas-goyal-axway commented on apidoc/NfcMiFareTagTechnology.yml
> +      type: Titanium.Buffer
It should be ```Array<Number>```

2021-03-02 05:25 UTC, vikas-goyal-axway commented on apidoc/NfcMiFareTagTechnology.yml
> +    - name: sw1
```data``` parameter is not defined here

2021-03-02 05:25 UTC, vikas-goyal-axway commented on ios/Classes/TiNfcMiFareUltralightTagTechnology.m
> +  NSNumber *expectedResponseLengthData = [[args objectAtIndex:0] valueForKey:@"expectedResponseLength"];
```suggestion
  NSNumber *expectedResponseLengthData = [[args firstObject] valueForKey:@"expectedResponseLength"];
```

2021-03-02 05:25 UTC, vikas-goyal-axway commented on ios/Classes/TiNfcMiFareUltralightTagTechnology.m
> +  NSArray *commandData = [[args objectAtIndex:0] valueForKey:@"data"];
```suggestion
  NSArray *commandData = [[args firstObject] valueForKey:@"data"];
```

2021-03-02 05:25 UTC, vikas-goyal-axway commented on ios/Classes/TiNfcMiFareUltralightTagTechnology.m
> +  NSArray *commandData = [[args objectAtIndex:0] valueForKey:@"data"];
```suggestion
  NSArray *commandData = [[args firstObject] valueForKey:@"data"];
```

2021-03-03 06:15 UTC, fasihul-axway approved these changes

2021-03-03 09:52 UTC, vikas-goyal-axway approved these changes

2021-03-03 09:56 UTC, merged